image: registry.gitlab.com/feup-tbs/ldso18-19/t2g4/ci-image

before_script:
  - BRANCH_NAME=$(git branch | grep \* | cut -d ' ' -f2)
  - export SSHPASS=$USER_PASS

stages:
  - linter
  - testing
  - deploy

lint:
  stage: linter
  script:
    - cd filesForCI
    - composer install
    - php ./vendor/bin/phpcs ../Laravel/app --standard=PSR2 --exclude=Generic.Files.LineLength
    - php ./vendor/bin/phpcs ../Laravel/routes --standard=PSR2 --exclude=Generic.Files.LineLength

deploy-testing:
  stage: testing
  environment:
    name: testing
    url: http://46.101.156.192:8200
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/testing && chmod 777 script.sh && ./script.sh BRANCH_NAME"
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/testing && chmod 777 wait-on-health.sh && sh wait-on-health.sh"
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "docker exec -t laravel-test_web-prod_1 php ./vendor/bin/codecept build"
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "docker exec -t laravel-test_web-prod_1 php ./vendor/bin/codecept run acceptance"
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "docker exec -t laravel-test_web-prod_1 php ./vendor/bin/phpunit"

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: http://46.101.156.192:8000
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/staging && chmod 777 script.sh && ./script.sh"
  only:
   - project-development

deploy-production:
 stage: deploy
 environment:
   name: production
   url: http://46.101.156.192:8100
 script:
   - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/production && chmod 777 script.sh && ./script.sh"
 only:
   - master
