image: registry.gitlab.com/feup-tbs/ldso18-19/t2g4/ci-image

before_script:
  - export SSHPASS=$USER_PASS

stages:
  - linter
  - testing
  - deploy

lint:
  stage: linter
  script:
    - cd filesForCI
    - composer install
    - php ./vendor/bin/phpcs ../Laravel/app --standard=PSR2 --exclude=Generic.Files.LineLength
    - php ./vendor/bin/phpcs ../Laravel/routes --standard=PSR2 --exclude=Generic.Files.LineLength

testing:
  stage: testing
  script:
    - cd Laravel
    - composer install
    - php ./vendor/bin/codecept build
    - php ./vendor/bin/codecept run
    - php ./vendor/bin/phpunit

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: http://46.101.156.192:8000
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/staging && chmod 777 script.sh && ./script.sh"
  only:
   - project-development

deploy-production:
 stage: deploy
 environment:
   name: production
   url: http://46.101.156.192:8100
 script:
   - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/production && chmod 777 script.sh && ./script.sh"
 only:
   - master
