image: registry.gitlab.com/feup-tbs/ldso18-19/t2g4/ci-image

services:
- docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - export SSHPASS=$USER_PASS

stages:
  - linter
  - testing
  - deploy

lint:
  stage: linter
  script:
    - cd filesForCI
    - composer install
    - php ./vendor/bin/phpcs ../Laravel/app --standard=PSR2 --exclude=Generic.Files.LineLength
    - php ./vendor/bin/phpcs ../Laravel/routes --standard=PSR2 --exclude=Generic.Files.LineLength

testing:
  stage: testing
  script:
    - cd Laravel
    - wget https://pastebin.com/raw/EmMfU0UA --output-document=.env
    - docker-compose up --build
    - docker exec -t laravel_web_1 php ./vendor/bin/codecept build
    - docker exec -t laravel_web_1 php ./vendor/bin/codecept run acceptance
    - docker exec -t laravel_web_1 php ./vendor/bin/phpunit

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: http://46.101.156.192:8000
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/staging && chmod 777 script.sh && ./script.sh"
  only:
   - project-development

deploy-production:
 stage: deploy
 environment:
   name: production
   url: http://46.101.156.192:8100
 script:
   - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/production && chmod 777 script.sh && ./script.sh"
 only:
   - master
