image: registry.gitlab.com/feup-tbs/ldso18-19/t2g4/ci-image

services:
- docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - export SSHPASS=$USER_PASS

stages:
  - testing
  - linter
  - deploy

lint:
  stage: linter
  script:
    - cd filesForCI
    - composer install
    - php ./vendor/bin/phpcs ../Laravel/app --standard=PSR2 --exclude=Generic.Files.LineLength
    - php ./vendor/bin/phpcs ../Laravel/routes --standard=PSR2 --exclude=Generic.Files.LineLength

testing:
  stage: testing
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "docker exec -t laravel-test_web_1 php ./vendor/bin/codecept build"
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "docker exec -t laravel-test_web_1 php ./vendor/bin/codecept run acceptance"
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "docker exec -t laravel-test_web_1 php ./vendor/bin/phpunit"

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: http://46.101.156.192:8000
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/staging && chmod 777 script.sh && ./script.sh"
  only:
   - project-development

deploy-production:
 stage: deploy
 environment:
   name: production
   url: http://46.101.156.192:8100
 script:
   - sshpass -e ssh -o StrictHostKeyChecking=no root@46.101.156.192 "cd ~/production && chmod 777 script.sh && ./script.sh"
 only:
   - master
