image: registry.gitlab.com/feup-tbs/ldso18-19/t2g3/base-ci-image

services:
- docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - export SSHPASS=$USER_PASS

stages:
  - deploy

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: http://46.101.156.192:8000
  script:
    - cp -r server/seed/stagingDB filesNeededForDeployment/staging/seed
    - sshpass -e scp -o stricthostkeychecking=no -r filesNeededForDeployment/staging/seed root@165.227.159.2:./staging
    - sshpass -e ssh -o StrictHostKeyChecking=no root@165.227.159.2 "export CI_JOB_TOKEN=$CI_JOB_TOKEN && cd staging && chmod 777 script.sh && ./script.sh"
  only:
    - project-development

deploy-production:
  stage: deploy
  environment:
    name: production
    url: http://46.101.156.192:8100
  script:
    - cp -r server/seed/productionDB filesNeededForDeployment/production/seed
    - sshpass -e scp -o stricthostkeychecking=no -r filesNeededForDeployment/production/seed root@165.227.159.2:./production
    - sshpass -e ssh -o StrictHostKeyChecking=no root@165.227.159.2 "export CI_JOB_TOKEN=$CI_JOB_TOKEN && cd production && chmod 777 script.sh && ./script.sh"
  only:
    - master

