version: '3'
services:

  web-prod:
    image: hitalos/laravel:latest
    ports:
        - 8200:80
    volumes:
        - ./:/var/www
    depends_on:
        - postgres-test
    environment:
        DB_HOST: postgres-test
        DB_DATABASE: test
        DB_USERNAME: test
        DB_PASSWORD: pg!fcp
        DB_CONNECTION: pgsql
    command: bash -c "composer install
             && composer update
             && php artisan db:seed
             && php artisan serve --host=0.0.0.0 --port=80"

  postgres-test:
    image: postgres:9.4
    restart: always
    environment:
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: pg!fcp
        PGPORT: 5430
    ports:
      - 5430:5430
